function PlotToFileColorPDF(gcf, filename, width_cm, height_cm)
    set(gcf, 'Units', 'centimeters');
    set(gcf, 'Position', [0, 0, width_cm, height_cm]);
    
    exportgraphics(gcf, filename, ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'white', ...
        'Resolution', 1200, ...
        'Width',  width_cm,...
        'Height', height_cm,...
        'Padding', "tight",...
        'Units', "centimeters");
end